---
- name: change chown of tomcat directory wit -r
  ansible.builtin.file:
    path: /opt/tomcat/apache-tomcat-10.1.59
    owner: tomcat
    group: tomcat
    recurse: yes

- name: set permissions chmod +x on bin directory 
  ansible.builtin.file:
    path: /opt/tomcat/apache-tomcat-10.1.59/bin
    mode: '+x'
    recurse: yes
    owner: tomcat
    group: tomcat

  