#SPDX-License-Identifier: MIT-0
---
# tasks file for mywebrole
- name: install webserver 
  apt:
    name: "{{webserver_package}}"
    state: present
  notify: restartwebserver

- name: copy a file
  copy:
    src:  templates/mystaticfile
    dest: /var/www/html/index.html
  notify: restartwebserver


